version: '3.8'

services:
  redis:
    image: redis:7.4.3
    container_name: redis-server
    restart: no
    ports:
      - "6379:6379"
    command: ["redis-server", "--requirepass", "redis"]

  authverify:
    build:
      context: ./AuthVerifyMicroservice
      dockerfile: Dockerfile
    container_name: authverify-service
    ports:
      - "8080:8080"
    depends_on:
      - redis